services:
  database:
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@database:5432/postgres
      DB_ECHO: "False"
      DEBUG: "True"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./static:/app/static
    restart: unless-stopped


volumes:
  postgres_data:
  